"""added avg_cost_ppn to productavgcostcache table

Revision ID: 15e015b74f1c
Revises: fc73838a0608
Create Date: 2025-10-31 18:55:16.583966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e015b74f1c'
down_revision: Union[str, None] = 'fc73838a0608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_avg_cost_cache', sa.Column('avg_cost_ppn', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_avg_cost_cache', 'avg_cost_ppn')
    # ### end Alembic commands ###
