"""update db

Revision ID: 28e8ec17307a
Revises: dfe06286936f
Create Date: 2025-09-26 13:36:38.134722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e8ec17307a'
down_revision: Union[str, None] = 'dfe06286936f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_no', sa.Numeric(), nullable=False))
    op.add_column('accounts', sa.Column('alias', sa.String(), nullable=True))
    op.drop_column('accounts', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'alias')
    op.drop_column('accounts', 'account_no')
    # ### end Alembic commands ###
