"""add product_avg_cost_cache table

Revision ID: 2e941b3888ce
Revises: 343d2fe4a87e
Create Date: 2025-10-08 02:40:18.417030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e941b3888ce'
down_revision: Union[str, None] = 'a85bd5ebd2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_avg_cost_cache',
    sa.Column('avg_cost', sa.Float(), nullable=True),
    sa.Column('total_qty_in', sa.Float(), nullable=True),
    sa.Column('total_value_in', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.alter_column('color_kitchen_batch_details', 'unit_cost_used',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('color_kitchen_entry_details', 'unit_cost_used',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('stock_movement_details', 'unit_cost_used',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_movement_details', 'unit_cost_used',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('color_kitchen_entry_details', 'unit_cost_used',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('color_kitchen_batch_details', 'unit_cost_used',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.drop_table('product_avg_cost_cache')
    # ### end Alembic commands ###
