"""stock opname difference reverse calc

Revision ID: 4b9b1599af4c
Revises: f96d89ca45e2
Create Date: 2025-10-06 03:17:52.431634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9b1599af4c'
down_revision: Union[str, None] = 'f96d89ca45e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
