"""update account_no unique

Revision ID: 50ef075133eb
Revises: c63d08679b86
Create Date: 2025-09-26 13:59:13.317685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ef075133eb'
down_revision: Union[str, None] = 'c63d08679b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_account_no'), 'accounts', ['account_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_account_no'), table_name='accounts')
    # ### end Alembic commands ###
