"""allow product code null

Revision ID: 8c0b21986695
Revises: 50ef075133eb
Create Date: 2025-09-26 15:45:45.584175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0b21986695'
down_revision: Union[str, None] = '50ef075133eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'products', ['name'])
    op.create_unique_constraint(None, 'products', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.alter_column('products', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
