"""added type column to account parent

Revision ID: 8c1c7d194a3b
Revises: 15e015b74f1c
Create Date: 2025-11-03 15:06:38.583951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1c7d194a3b'
down_revision: Union[str, None] = '15e015b74f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_parents', sa.Column('account_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_parents', 'account_type')
    # ### end Alembic commands ###
