"""Initial schema

Revision ID: a582d8c5be42
Revises: 
Create Date: 2025-10-07 13:24:36.643009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a582d8c5be42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_no', sa.Numeric(), nullable=False),
    sa.Column('account_type', sa.Enum('Goods', 'Service', name='account_type_enum'), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_no'), 'accounts', ['account_no'], unique=True)
    op.create_table('color_kitchen_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_opnames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['design_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('purchasings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('purchase_order', sa.String(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_kitchen_batch_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['color_kitchen_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_kitchen_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('rolls', sa.Integer(), nullable=True),
    sa.Column('paste_quantity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['color_kitchen_batches.id'], ),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('ref', sa.Enum('Purchasing', 'Ck', 'StockMovement', 'StockOpname', name='ledger_ref_enum'), nullable=False),
    sa.Column('ref_code', sa.String(), nullable=False),
    sa.Column('location', sa.Enum('Gudang', 'Kitchen', 'Usage', 'Opname', name='ledger_location_enum'), nullable=False),
    sa.Column('quantity_in', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('quantity_out', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchasing_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ppn', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pph', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('dpp', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_no', sa.String(), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('purchasing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchasing_id'], ['purchasings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movement_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('stock_movement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['stock_movement_id'], ['stock_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_opname_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_quantity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('physical_quantity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=18, scale=2), sa.Computed('system_quantity - physical_quantity', ), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('stock_opname_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['stock_opname_id'], ['stock_opnames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_kitchen_entry_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_kitchen_entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_kitchen_entry_id'], ['color_kitchen_entries.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('color_kitchen_entry_details')
    op.drop_table('stock_opname_details')
    op.drop_table('stock_movement_details')
    op.drop_table('purchasing_details')
    op.drop_table('ledgers')
    op.drop_table('color_kitchen_entries')
    op.drop_table('color_kitchen_batch_details')
    op.drop_table('purchasings')
    op.drop_table('products')
    op.drop_table('designs')
    op.drop_table('suppliers')
    op.drop_table('stock_opnames')
    op.drop_table('stock_movements')
    op.drop_table('design_types')
    op.drop_table('color_kitchen_batches')
    op.drop_index(op.f('ix_accounts_account_no'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
