"""ck update

Revision ID: bb595b17fc96
Revises: b79d91b48885
Create Date: 2025-10-01 15:31:44.625830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb595b17fc96'
down_revision: Union[str, None] = 'b79d91b48885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_kitchen_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_kitchen_batch_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['color_kitchen_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_kitchen_entry_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_kitchen_entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_kitchen_entry_id'], ['color_kitchen_entries.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('color_kitchen_details')
    op.add_column('color_kitchen_entries', sa.Column('rolls', sa.Integer(), nullable=True))
    op.add_column('color_kitchen_entries', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'color_kitchen_entries', 'color_kitchen_batches', ['batch_id'], ['id'])
    op.drop_column('color_kitchen_entries', 'quantity')
    op.add_column('purchasing_details', sa.Column('pph', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchasing_details', 'pph')
    op.add_column('color_kitchen_entries', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'color_kitchen_entries', type_='foreignkey')
    op.drop_column('color_kitchen_entries', 'batch_id')
    op.drop_column('color_kitchen_entries', 'rolls')
    op.create_table('color_kitchen_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color_kitchen_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['color_kitchen_entry_id'], ['color_kitchen_entries.id'], name='color_kitchen_details_color_kitchen_entry_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='color_kitchen_details_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='color_kitchen_details_pkey')
    )
    op.drop_table('color_kitchen_entry_details')
    op.drop_table('color_kitchen_batch_details')
    op.drop_table('color_kitchen_batches')
    # ### end Alembic commands ###
