"""add design type as table

Revision ID: e10c820dcd57
Revises: 8c0b21986695
Create Date: 2025-09-29 13:53:49.085620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e10c820dcd57'
down_revision: Union[str, None] = '8c0b21986695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('designs', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'designs', 'design_types', ['type_id'], ['id'])
    op.drop_column('designs', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designs', sa.Column('type', postgresql.ENUM('Hyget', 'DkPe40', 'Billabong', 'BbTr', 'Rasfur', 'Rib', 'PolyHanduk', 'Tc25', 'Pe30', 'Pe20', name='designkaintype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'designs', type_='foreignkey')
    op.drop_column('designs', 'type_id')
    op.drop_table('design_types')
    # ### end Alembic commands ###
